In [ ]:
import torch

In [ ]:
x = torch.empty(2,5)

In [ ]:
x.fill_(1.25)

tensor([[1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
        [1.2500, 1.2500, 1.2500, 1.2500, 1.2500]])

In [ ]:
x.size()

torch.Size([2, 5])

In [ ]:
x.mean()

tensor(1.2500)

In [ ]:
x.std()

tensor(0.)

In [ ]:
x.sum()

tensor(12.5000)

In [ ]:
x.sum().item()

12.5

In [ ]:
x = torch.tensor([[11.,12.,12.],[21.,22.,23.]])

In [ ]:
x[1,2]

tensor(23.)

In [ ]:
x = torch.tensor([10.,20.,30.])
y = torch.tensor([11.,21.,31.])
x + y

tensor([21., 41., 61.])

In [ ]:
x * y

tensor([110., 420., 930.])

In [ ]:
x ** 2

tensor([100., 400., 900.])

In [ ]:
m = torch.tensor([[0.,0.,3.],[0.,2.,0.],[1.,0.,0.]])

In [ ]:
m.mv(x)

tensor([90., 40., 10.])

In [ ]:
m @ x # matrix multiplication

tensor([90., 40., 10.])

In [ ]:
x = torch.tensor([ 1., 2. ])
y = torch.tensor([ 4., 5. ])
z = torch.tensor([ 7., 3. ])
x.requires_grad

False

In [ ]:
(x + y).requires_grad

False

In [ ]:
z.requires_grad = True
(x + z).requires_grad

True

In [ ]:
x = torch.tensor([1., 10.])
x.requires_grad = True

In [ ]:
x = torch.tensor([1, 10])  # cant do int just float
x.requires_grad = True

RuntimeError: ignored

In [ ]:
t = torch.tensor([1., 2., 4.]).requires_grad_()
u = torch.tensor([10., 20.]).requires_grad_()
a = t.pow(2).sum() + u.log().sum()
torch.autograd.grad(a, (t, u))

(tensor([2., 4., 8.]), tensor([0.1000, 0.0500]))